{"trial_id": "0000", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "activation", "default": "relu", "conditions": [], "values": ["relu", "tanh", "sigmoid"], "ordered": false}}, {"class_name": "Int", "config": {"name": "first_units", "default": null, "conditions": [], "min_value": 1, "max_value": 90, "step": 5, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "num_layers", "default": null, "conditions": [], "min_value": 1, "max_value": 5, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_0", "default": null, "conditions": [], "min_value": 1, "max_value": 30, "step": 5, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_1", "default": null, "conditions": [], "min_value": 1, "max_value": 30, "step": 5, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_2", "default": null, "conditions": [], "min_value": 1, "max_value": 30, "step": 5, "sampling": "linear"}}], "values": {"activation": "tanh", "first_units": 6, "num_layers": 3, "units_0": 1, "tuner/epochs": 3, "tuner/initial_epoch": 0, "tuner/bracket": 2, "tuner/round": 0, "units_1": 1, "units_2": 1}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/Users/jctransitllc/Desktop/anaconda3/envs/PythonData/lib/python3.7/site-packages/keras_tuner/engine/base_tuner.py\", line 250, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/jctransitllc/Desktop/anaconda3/envs/PythonData/lib/python3.7/site-packages/keras_tuner/engine/base_tuner.py\", line 215, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/jctransitllc/Desktop/anaconda3/envs/PythonData/lib/python3.7/site-packages/keras_tuner/tuners/hyperband.py\", line 404, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/jctransitllc/Desktop/anaconda3/envs/PythonData/lib/python3.7/site-packages/keras_tuner/engine/tuner.py\", line 286, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/Users/jctransitllc/Desktop/anaconda3/envs/PythonData/lib/python3.7/site-packages/keras_tuner/engine/tuner.py\", line 213, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"/Users/jctransitllc/Desktop/anaconda3/envs/PythonData/lib/python3.7/site-packages/keras_tuner/engine/hypermodel.py\", line 144, in fit\n    return model.fit(*args, **kwargs)\n  File \"/Users/jctransitllc/Desktop/anaconda3/envs/PythonData/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py\", line 727, in fit\n  File \"/Users/jctransitllc/Desktop/anaconda3/envs/PythonData/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_arrays.py\", line 675, in fit\n  File \"/Users/jctransitllc/Desktop/anaconda3/envs/PythonData/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_arrays.py\", line 450, in model_iteration\n  File \"/Users/jctransitllc/Desktop/anaconda3/envs/PythonData/lib/python3.7/site-packages/tensorflow_core/python/keras/callbacks.py\", line 299, in on_epoch_end\n  File \"/Users/jctransitllc/Desktop/anaconda3/envs/PythonData/lib/python3.7/site-packages/keras_tuner/engine/tuner_utils.py\", line 206, in on_epoch_end\n    self._save_model()\n  File \"/Users/jctransitllc/Desktop/anaconda3/envs/PythonData/lib/python3.7/site-packages/keras_tuner/engine/tuner_utils.py\", line 216, in _save_model\n    self.filepath, self.model.distribute_strategy\nAttributeError: 'Sequential' object has no attribute 'distribute_strategy'\n"}